### ISSUE TITLE
Product Factory Filtering

### ISSUE THREAD

**Issue by nrod80** [BearGrappler/cnyStore#50]
Create the routes/methods to filter based on possible configurations

**Comment by nrod80** [comment]
I think I'm going to hold off on this until I have a better idea of what the results of the question waterfall will be

**Comment by clocasto** [comment]
The question waterfall will produce an object which has seven properties: computer, type, cpu, ram, gpu, hdd, and size. Computer and type will take arrays of strings and the rest will be integers from 0 -> n. It will look like the following:
{ computer :  ['laptop'],  type :  ['gamer, 'artist', etc...], cpu : 0, ram : 1, gpu : 2, hdd : 9, size : 8 }
